#! /usr/bin/env sh 

dir=`basename $1`

echo Starting pipeline `date`
echo Creating $dir

covid_run_dir=/local/incoming/covid/runs/${dir}/
export_dir=/vol/sars2/jdavis/Sarah/
ssh_id_file=/local/incoming/covid/config/covid_rsa
rsa_file=covid_`whoami`_rsa

# Create infrastructure
mkdir /local/incoming/covid/runs/${dir}
for d in variants output depth bam samples staging ; do echo Creating ${dir}/${d}; mkdir -p ${covid_run_dir}/${d} ; done
cp /local/incoming/covid/scripts/Makefile  ${covid_run_dir}
cp /local/incoming/covid/config/MN908947.3.trimmed.fa ${covid_run_dir}

current_dir=`pwd`
cd ${covid_run_dir}
ln -s samples/ reads
cd ${current_dir}

# Copy files
echo "Copying fastq's"
find $1 -name "*.fastq.gz" -exec cp {} ${covid_run_dir}/samples/ \;
find $1 -name "*.sample-mapping.tsv" -exec cp {} ${covid_run_dir}/samples/ \;
echo Found `ls ${covid_run_dir}/samples/ | wc -l` sequence files

# Assembly
sh /local/incoming/covid/scripts/assembly.sh ${covid_run_dir} 

sh /local/incoming/covid/scripts/process-run.sh ${covid_run_dir}

# Create plots
echo Creating plots `date`
prefix=`date +%y%m%d-%H%M`
cd /local/incoming/covid/aggregate
time make -i -j 20 > ${prefix}.plotting.out 2> ${prefix}.plotting.error 
mkdir -p /local/incoming/covid/aggregate/${prefix}
cp -r /local/incoming/covid/aggregate/current/* /local/incoming/aggregate/${prefix}/
echo Done pipeline `date`
